add SQL script for people table
NikShein/Movies pull request #2
Opened 2022-02-17 15:49 UTC by NikShein

2022-02-17 16:31 UTC, nikitabls commented on SQL/people.sql
> +    DateOfBirth INTEGER
It is better to use the Date type for storing dates

2022-02-17 16:34 UTC, nikitabls commented on SQL/people.sql
> +CREATE TABLE People
It is also better to name SQL scripts more verbosely, so we can know what this script is doing:
For example, this one is better to be named "create_people_table.sql"

2022-02-18 09:05 UTC, belousnikita commented on SQL/people.sql
> +    Id SERIAL PRIMARY KEY,
Why ID is a SERIAL type?

2022-02-18 09:06 UTC, belousnikita commented on SQL/people.sql
> +    DateOfBirth INTEGER
For date it is better to use Date types

2022-02-18 09:08 UTC, belousnikita commented
Please use more verbose names for files

2022-02-18 09:25 UTC, belousnikita requested changes
Please see comments

2022-02-18 11:08 UTC, NikShein commented on SQL/people.sql
> +    Id SERIAL PRIMARY KEY,
`PostgreSQL has a special kind of database object generator called SERIAL. It is used to generate a sequence of integers which are often used as the Primary key of a table. When creating a table, this sequence of integers can be created as follows: CREATE TABLE table_name( id SERIAL );`

[PostgresSQL - Serial Type](https://www.geeksforgeeks.org/postgresql-serial/#:~:text=PostgreSQL%20has%20a%20special%20kind,Primary%20key%20of%20a%20table.&text=When%20creating%20a%20table%2C%20this,TABLE%20table_name(%20id%20SERIAL%20)%3B)

2022-02-18 11:59 UTC, belousnikita approved these changes

2022-02-18 11:59 UTC, merged